### PR TITLE
Fix warnings and set warnings as hard errors

### PR DESCRIPTION
**Pull request by GuillaumeGomez**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc @rahulreddy

**Comment by rahulreddy** [comment]
@ironman-machine

**Comment by rahulreddy** [comment]
@ironman-machine 
SCALITY_FEDERATION_BRANCH=ft/dep-patcher-ansible
SCALITY_INTEGRATION_BRANCH=fix/nimrod-build-dep

**Comment by rahulreddy** [comment]
end to end passed, merging this.

**Pull request merged**
