### PR TITLE
refactor(werelogs): export using ES6 standards

### PR DESCRIPTION
**Pull request by michael-zapata**
Update `index.js` to provide a `Logger` field to match expected
behaviour under ES6 or TypeScript

BREAKING CHANGE

### CODE REVIEW

**Comment by michael-zapata** [comment]
Fixes #75

**Comment by rahulreddy** [comment]
👍

**Comment by alexandre-merle** [comment]
:+1:

**Comment by michael-zapata** [comment]
Merging on behalf of @rahulreddy to get things going forward.

**Pull request merged**
