### PR TITLE
generateUid: Faster implementation

### PR DESCRIPTION
**Pull request by MathieuCassagne**
The way we used to generate uid for a request is not the fastest one.
This one is really faster and generate uid of the same look.
The base algorithm is taken from here: http://jcward.com/UUID.js
And is explained here: http://stackoverflow.com/a/21963136

### CODE REVIEW

**Comment by MathieuCassagne** [comment]
@DavidPineauScality: It is now in the code.

**Comment by DavidPineauScality** [comment]
And now with the right ultron version:
@ironman-machine r+

**Comment by DavidPineauScality** [comment]
@ironman-machine r- r+

**Comment by rahulreddy** [comment]
It's a nice enhancement. Can you please leave the PR open long enough for us to review here in SF? I am the project maintainer but I never got the chance to review this.

**Comment by DavidPineauScality** [comment]
Sorry about that, it's my fault: I was somehow in the mindset that I was still handling werelogs.

**Pull request merged**
