### PR TITLE
improvement: S3C-2292 Upgrade node version

### PR DESCRIPTION
**Pull request by Katherinelaue1**
*What does this PR do, and why do we need it?*
Upgrade node version as node version 6 is not supported

*Which issue does this PR fix?*
fixes #S3C-2292

*Special notes for your reviewers:*

### CODE REVIEW

**Comment by Katherinelaue1** [comment]
@bert-e reset

**Comment by Katherinelaue1** [comment]
@bert-e force_reset

**Comment by Katherinelaue1** [comment]
@bert-e status

**Review by ssalaues — APPROVED** [review]

**Review by anurag4DSB — APPROVED** [review]

**Review by tmacro — APPROVED** [review]

**Review by rahulreddy — APPROVED** [review]

**Comment by rahulreddy** [comment]
Congratulations on your first PR @Katherinelaue1 !

**Comment by Katherinelaue1** [comment]
@bert-e approve

**Pull request merged**
